$(document).ready(function(){
  $(window).scroll(function(){
    if($(this).scrollTop()){
      $('header').addClass('sticky');
    }
    else{
      $('header').removeClass('sticky');
    }
  });
});
$('.owl-carousel').owlCarousel({
  loop:true,
  margin:10,
  dots:true,
  autoplay: true,
  autoplayTimeout:4000,
  autoplayHoverPause:true,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:1
      },
      1000:{
          items:1
      }
  }
})